# Generated by Django 3.2.15 on 2024-05-22 15:45

from django.db import migrations, models
import file_upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=300)),
                ('user_name', models.CharField(max_length=300)),
                ('file', models.FileField(null=True, upload_to=file_upload.models.file_path_change)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('reply_list', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
