# Generated by Django 3.2.15 on 2024-05-08 17:41

from django.db import migrations, models
import file_upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='본인 이름', max_length=50, null=True)),
                ('file', models.FileField(null=True, upload_to=file_upload.models.file_path_change)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('users', models.CharField(blank=True, max_length=150, null=True)),
                ('group', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
