# Generated by Django 5.0.6 on 2024-05-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_upload", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadfile",
            name="reply_list",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
