# Generated by Django 5.0.6 on 2024-05-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_upload", "0002_uploadfile_reply_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadfile",
            name="reply_list",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="uploadfile",
            name="users",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
